server:
  port: 8888
  tomcat:
    accept-count: 1000 
    max-threads: 1000
    max-connections: 2000


spring:
  application:
    name: exciting_utils
  banner:
    location: banners/喜逼.txt

logging:
  config: classpath:log4j2.xml
