server:
  port: 8888
  servlet:
    context-path: /exciting
  tomcat:
    accept-count: 100
    max-threads: 100
    max-connections: 200



spring:
  application:
    name: exciting_utils
  banner:
    location: banners/frog.txt
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://3.17.164.48:3306/exciting?autoReconnect=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: exciting
    password: q53qepqa
    driver-class-name: com.mysql.cj.jdbc.Driver

    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 100
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

#logging:
#  config: classpath:logback.xml
mybatis:
  mapper-locations: classpath*:**/*Mapper.xml
