server:
  port: 8888
  servlet:
    context-path: /exciting
  tomcat:
    accept-count: 100
    max-threads: 100
    max-connections: 200



spring:
  application:
    name: exciting_utils
  banner:
    location: banners/frog.txt
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://18.188.121.49:3306/exciting?autoReconnect=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: exciting
    password: q53qepqa
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.107.241
    username: admin
    password: admin
    virtualHost: /

#logging:
#  config: classpath:logback.xml
mybatis:
  mapper-locations: classpath*:**/*Mapper.xml
